# Generated by Django 5.1.3 on 2024-11-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_pair', models.CharField(max_length=6)),
                ('timestamp', models.DateTimeField()),
                ('exchange_rate', models.FloatField()),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['code']},
        ),
    ]
